version: '2'
services:
    selenium-worker-app:
        build: .
        image: selenium-worker
        environment:
        # - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - APPLICATION_SELENIUM_URL=http://hub:4444/wd/hub
        links:
        - selenium-hub:hub
        networks:
        - backend
        volumes:
        - "/var/log/service:/var/log/service"
        - "/var/log/data:/var/log/data"
    selenium-hub:
        image: selenium/hub
        ports:
        - 4444:4444
        networks:
        - backend
    chrome:
        image: selenium/node-chrome:2.47.1
        links:
        - selenium-hub:hub
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
        volumes:
        - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
        networks:
        - backend
    firefox:
        image: selenium/node-firefox
        links:
        - selenium-hub:hub
        environment:
            HUB_PORT_4444_TCP_ADDR: hub

        networks:
        - backend
networks:
    backend:
        driver: "bridge"
